<script lang="ts">
	import { onDestroy } from 'svelte';
	import { SCRIPT_VERSIONS, GITHUB_RAW_BASE } from '@gacha-tracker/shared';
	import { importWizard } from '$lib/stores/importWizard.svelte';
	import { connectImportSse, disconnectImportSse } from '$lib/stores/importSse.svelte';
	import WizardShell from '$lib/components/wizard/WizardShell.svelte';
	import WizardStep from '$lib/components/wizard/WizardStep.svelte';
	import CommandBlock from '$lib/components/wizard/CommandBlock.svelte';
	import ImportStatusDisplay from '$lib/components/wizard/ImportStatusDisplay.svelte';
	import { PUBLIC_API_URL } from '$env/static/public';
	import { ChevronRight, ChevronLeft, ExternalLink, Info, Clock } from 'lucide-svelte';

	let { data } = $props();

	const steps = ['Instructions', 'Run Script', 'Waiting...', 'Done!'];

	// Initialize store with data from loader
	$effect(() => {
		if (data.token) {
			importWizard.setToken(data.token, data.cursors);
		}
	});

	// Handle SSE connection based on step
	$effect(() => {
		if (importWizard.state.step === 2 || importWizard.state.step === 3) {
			connectImportSse(data.gameId, importWizard);
		} else if (importWizard.state.step === 4 || importWizard.state.step === 1) {
			disconnectImportSse();
		}
	});

	onDestroy(() => {
		disconnectImportSse();
		importWizard.reset();
	});

	const wizard = $derived(data.gameConfig.wizard);
	const sha = $derived(SCRIPT_VERSIONS[data.gameId as keyof typeof SCRIPT_VERSIONS]);
	const scriptUrl = $derived(wizard ? `${GITHUB_RAW_BASE}/${sha}/${wizard.scriptPath}` : '');

	// The PowerShell command to run
	const cursorsJson = $derived(data.cursors ? JSON.stringify(data.cursors) : '{}');
	const cleanApiUrl = $derived(PUBLIC_API_URL.replace(/\/+$/, ''));
	const command = $derived(
		`& ([scriptblock]::Create((irm "${scriptUrl}"))) -ImportToken "${data.token}" -Cursors '${cursorsJson}' -ApiUrl "${cleanApiUrl}"`
	);

	function handleNext() {
		importWizard.nextStep();
	}

	function handleBack() {
		importWizard.prevStep();
	}
</script>

<svelte:head>
	<title>Import {data.gameConfig.displayName} - Gacha Tracker</title>
</svelte:head>

<WizardShell
	{steps}
	currentStep={importWizard.state.step}
	gameDisplayName={data.gameConfig.displayName}
	gameId={data.gameId}
>
	{#if !wizard}
		<WizardStep title="Coming Soon" subtitle="Automated import is not yet available for this game.">
			<div class="py-12 flex flex-col items-center justify-center text-center space-y-4">
				<div
					class="w-16 h-16 rounded-full bg-zinc-800 flex items-center justify-center text-zinc-500 mb-2"
				>
					<Clock size={32} />
				</div>
				<p class="text-zinc-400 max-w-sm">
					We're currently working on the extraction script for <span class="text-zinc-100 font-bold"
						>{data.gameConfig.displayName}</span
					>. Check back soon!
				</p>
			</div>
			{#snippet footer()}
				<a
					href="/{data.gameId}"
					class="flex items-center gap-2 px-5 py-2 text-zinc-400 hover:text-zinc-100 transition-colors font-medium"
				>
					<ChevronLeft size={18} />
					Back to Game
				</a>
				<div></div>
			{/snippet}
		</WizardStep>
	{:else if importWizard.state.step === 1}
		<WizardStep
			title="Prepare Your History"
			subtitle="Before running the script, we need the game to refresh its local cache."
		>
			<div class="space-y-6">
				<div class="flex gap-4 p-4 rounded-xl bg-yellow-400/5 border border-yellow-400/20">
					<div
						class="shrink-0 w-10 h-10 rounded-lg bg-yellow-400 flex items-center justify-center text-zinc-900 shadow-lg shadow-yellow-400/10"
					>
						<Info size={20} />
					</div>
					<div class="text-sm leading-relaxed">
						<span class="font-bold text-yellow-400">Important:</span> The extraction script works by
						reading the temporary web cache generated by the game. If you haven't opened the {wizard.historyName.toLowerCase()}
						records recently, the cache might be empty or expired.
					</div>
				</div>

				<ol class="space-y-4">
					<li class="flex gap-4">
						<div
							class="shrink-0 w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center text-xs font-bold text-zinc-400"
						>
							1
						</div>
						<p class="text-zinc-300">
							Launch <span class="text-zinc-100 font-medium">{data.gameConfig.displayName}</span> and
							log in to your account.
						</p>
					</li>
					<li class="flex gap-4">
						<div
							class="shrink-0 w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center text-xs font-bold text-zinc-400"
						>
							2
						</div>
						<p class="text-zinc-300">
							Open the <span class="text-zinc-100 font-medium">{wizard.historyName}</span> menu,
							then click on
							<span class="text-zinc-100 font-medium">{wizard.recordsName}</span>.
						</p>
					</li>
					<li class="flex gap-4">
						<div
							class="shrink-0 w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center text-xs font-bold text-zinc-400"
						>
							3
						</div>
						<p class="text-zinc-300">
							Wait for the history to load. You don't need to scroll through all pages.
						</p>
					</li>
					<li class="flex gap-4">
						<div
							class="shrink-0 w-6 h-6 rounded-full bg-zinc-800 flex items-center justify-center text-xs font-bold text-zinc-400"
						>
							4
						</div>
						<p class="text-zinc-300">
							Return to this window and click <span class="text-zinc-100 font-medium">Next</span>.
						</p>
					</li>
				</ol>

				<details class="group border border-zinc-800 rounded-xl bg-zinc-900/50 overflow-hidden">
					<summary
						class="p-4 flex items-center justify-between cursor-pointer list-none hover:bg-zinc-800/50 transition-colors"
					>
						<span class="text-sm font-medium text-zinc-300">Why is this needed?</span>
						<ChevronRight
							size={16}
							class="text-zinc-500 group-open:rotate-90 transition-transform"
						/>
					</summary>
					<div class="p-4 border-t border-zinc-800 text-sm text-zinc-400 leading-relaxed space-y-2">
						<p>
							{data.gameConfig.displayName} uses a secure URL to fetch your gacha history. This URL is
							stored in a temporary local file on your computer whenever you open the history in-game.
						</p>
						<p>
							Our script finds this file, extracts the URL, and securely sends your pull data
							directly to our database. We never see your login credentials.
						</p>
					</div>
				</details>
			</div>

			{#snippet footer()}
				<div></div>
				<button
					onclick={handleNext}
					class="flex items-center gap-2 px-6 py-2.5 bg-yellow-400 hover:bg-yellow-500 text-zinc-950 rounded-xl font-bold transition-all shadow-lg shadow-yellow-400/20 active:scale-95"
				>
					Next
					<ChevronRight size={18} />
				</button>
			{/snippet}
		</WizardStep>
	{:else if importWizard.state.step === 2}
		<WizardStep
			title="Run the Script"
			subtitle="Copy and paste the command below into your PowerShell terminal."
		>
			<div class="space-y-6">
				<p class="text-zinc-300">
					Open <span class="font-bold text-zinc-100">Windows PowerShell</span> (search for "PowerShell"
					in the Start menu), paste the command, and press Enter.
				</p>

				<CommandBlock {command} />

				<div class="p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 space-y-3">
					<div class="flex items-start gap-3">
						<Info size={18} class="text-zinc-400 shrink-0 mt-0.5" />
						<div class="text-sm text-zinc-400 leading-relaxed">
							<span class="text-zinc-200 font-medium italic block mb-1">Privacy & Security:</span>
							The command downloads a verified PowerShell script directly from our official GitHub repository.
							You can verify the code at any time by visiting the repository.
						</div>
					</div>
				</div>

				<div class="flex items-center gap-2 text-xs text-zinc-500 italic">
					<div class="w-2 h-2 rounded-full bg-yellow-400 animate-pulse"></div>
					Listening for your script to start...
				</div>
			</div>

			{#snippet footer()}
				<button
					onclick={handleBack}
					class="flex items-center gap-2 px-5 py-2 text-zinc-400 hover:text-zinc-100 transition-colors font-medium"
				>
					<ChevronLeft size={18} />
					Back
				</button>
				<button
					onclick={handleNext}
					class="px-6 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-xl font-semibold transition-all border border-zinc-700 active:scale-95"
				>
					I've run it
				</button>
			{/snippet}
		</WizardStep>
	{:else if importWizard.state.step === 3}
		<WizardStep title="Live Import Status" subtitle="The script is communicating with our servers.">
			<ImportStatusDisplay status={importWizard.state.status} result={importWizard.state.result} />

			{#snippet footer()}
				<button
					onclick={handleBack}
					class="flex items-center gap-2 px-5 py-2 text-zinc-400 hover:text-zinc-100 transition-colors font-medium"
				>
					<ChevronLeft size={18} />
					Back
				</button>
				<div></div>
			{/snippet}
		</WizardStep>
	{:else if importWizard.state.step === 4}
		<WizardStep title="Success!" subtitle="Your pull history has been updated.">
			<ImportStatusDisplay status="success" result={importWizard.state.result} />

			<div class="grid grid-cols-2 gap-4 mt-4">
				<a
					href="/{data.gameId}"
					class="flex flex-col items-center justify-center p-6 rounded-2xl bg-zinc-900 border border-zinc-800 hover:border-yellow-400/30 hover:bg-zinc-800 transition-all group"
				>
					<div
						class="w-12 h-12 rounded-full bg-zinc-800 flex items-center justify-center text-zinc-400 mb-3 group-hover:bg-yellow-400/10 group-hover:text-yellow-400 transition-colors"
					>
						<ExternalLink size={24} />
					</div>
					<span class="font-bold text-zinc-100">View History</span>
					<span class="text-xs text-zinc-500">Check your new pity counters</span>
				</a>

				<button
					onclick={() => {
						importWizard.reset();
						window.location.reload(); // Force re-fetch of token
					}}
					class="flex flex-col items-center justify-center p-6 rounded-2xl bg-zinc-900 border border-zinc-800 hover:border-yellow-400/30 hover:bg-zinc-800 transition-all group"
				>
					<div
						class="w-12 h-12 rounded-full bg-zinc-800 flex items-center justify-center text-zinc-400 mb-3 group-hover:bg-yellow-400/10 group-hover:text-yellow-400 transition-colors"
					>
						<ChevronLeft size={24} />
					</div>
					<span class="font-bold text-zinc-100">Import Again</span>
					<span class="text-xs text-zinc-500">Add pulls for another account</span>
				</button>
			</div>

			{#snippet footer()}
				<div></div>
				<a
					href="/dashboard"
					class="px-8 py-3 bg-zinc-100 hover:bg-white text-zinc-950 rounded-2xl font-bold transition-all shadow-xl active:scale-95"
				>
					Back to Dashboard
				</a>
			{/snippet}
		</WizardStep>
	{/if}
</WizardShell>

<style>
	/* Custom scrollbar for details content */
	details div::-webkit-scrollbar {
		width: 4px;
	}
	details div::-webkit-scrollbar-thumb {
		background: #27272a;
		border-radius: 10px;
	}
</style>
